### ISSUE TITLE
'Pattern matched multiple keys' error raised when trying to train

### ISSUE THREAD

**Issue by jonpedros** [fabiocarrara/meye#36]
Hello! Thank you very much for developing such a helpful tool.

I've been trying to train a network from my labeled frames, but I'm running into an error:

`Traceback (most recent call last):
  File "C:\Users\systemses\downloads\pupillometry\meye-master\train.py", line 161, in <module>
    main(args)
  File "C:\Users\systemses\downloads\pupillometry\meye-master\train.py", line 38, in main
    print(exp)
  File "C:\Users\systemses\downloads\pupillometry\meye-master\expman\experiment.py", line 162, in __str__
    with pd.option_context('display.width', None), pd.option_context('max_columns', None):
  File "C:\Users\systemses\anaconda3\envs\tensorflow\lib\site-packages\pandas\_config\config.py", line 434, in __enter__
    self.undo = [(pat, _get_option(pat, silent=True)) for pat, val in self.ops]
  File "C:\Users\systemses\anaconda3\envs\tensorflow\lib\site-packages\pandas\_config\config.py", line 434, in <listcomp>
    self.undo = [(pat, _get_option(pat, silent=True)) for pat, val in self.ops]
  File "C:\Users\systemses\anaconda3\envs\tensorflow\lib\site-packages\pandas\_config\config.py", line 128, in _get_option
    key = _get_single_key(pat, silent)
  File "C:\Users\systemses\anaconda3\envs\tensorflow\lib\site-packages\pandas\_config\config.py", line 116, in _get_single_key
    raise OptionError("Pattern matched multiple keys")
pandas._config.config.OptionError: 'Pattern matched multiple keys'`

**Comment by jonpedros** [comment]
Changed pandas version to 1.3.5 and it worked!
